{% set version = "1.1.4" %}

package:
  name: runc
  version: {{ version }}

source:
  - url: https://github.com/opencontainers/runc/releases/download/v{{ version }}/runc.tar.xz
    sha256: 9f5972715dffb0b2371e4d678c1206cc8c4ec5eb80f2d48755d150bac49be35b

build:
  number: 0
  skip: true  # [not linux]
  # Binary relocation causes:
  #   runc: symbol lookup error: runc: undefined symbol: seccomp_api_get
  # because of https://github.com/opencontainers/runc/commit/0a8e4117e7f715d5fbeef398405813ce8e88558b
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cgo') }}
    - go-licenses
    - make
    - pkg-config
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libseccomp
  run:
    - libseccomp

test:
  commands:
    - runc --help
    - runc --version

about:
  home: https://github.com/opencontainers/runc
  dev_url: https://github.com/opencontainers/runc
  doc_url: https://github.com/opencontainers/runc
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty-licenses/
  summary: CLI tool for spawning and running containers according to the OCI specification
  description: |
    runc is a command line client for running applications packaged according to the Open Container Initiative (OCI) format and is a compliant implementation of the Open Container Initiative specification.

    runc integrates well with existing process supervisors to provide a production container runtime environment for applications. It can be used with your existing process monitoring tools and the container will be spawned as a direct child of the process supervisor.

    Containers are configured using bundles. A bundle for a container is a directory that includes a specification file named "config.json" and a root filesystem. The root filesystem contains the contents of the container.

    To start a new instance of a container:

    > runc start [ -b bundle ] <container-id>

    Where "<container-id>" is your name for the instance of the container that you are starting. The name you provide for the container instance must be unique on your host. Providing the bundle directory using "-b" is optional. The default value for "bundle" is the current directory.

extra:
  recipe-maintainers:
    - mbargull
    - h-vetinari
